const Products = [
  {
    pid: 1,
    categoryName: "Self Help",
    author: "Morgan Housel",
    name: "Psychology of Money",
    price: "230",
    fakePrice: "450",
    img: "/Imgs/Products/psychologyOfMoney.jpg",
  },

  {
    pid: 2,
    categoryName: "Self Help",
    author: "Brian Stracy",
    name: "Eat that Frog",
    price: "150",
    fakePrice: "251",
    img: "/Imgs/Products/eatThatFrog.jpg",
  },
  {
    pid: 3,
    categoryName: "Self Help",
    author: "Napolean Hill",
    name: "Think and Grow Rich",
    price: "235",
    fakePrice: "495",
    img: "/Imgs/Products/thinkAndGrowRich.jpg",
  },
  {
    pid: 4,
    categoryName: "Self Help",
    author: "Dale Carnegie",
    name: "how to win Friends and Influence People",
    price: "230",
    fakePrice: "450",
    img: "/Imgs/Products/howtoWInFriends.jpg",
  },
  {
    pid: 5,
    categoryName: "Psychology",
    author: "Daniel Kehnman",
    name: "Thinking Fast and Slow",
    price: "300",
    fakePrice: "500",
    img: "/Imgs/Products/thinkingFastAndSlow.jpg",
  },
  {
    pid: 6,
    categoryName: "psychology",
    author: "David Epstien",
    name: "Range",
    price: "399",
    fakePrice: "699",
    img: "/Imgs/Products/range.jpg",
  },
  {
    pid: 7,
    categoryName: "Romance",
    author: "Colen Hoover",
    name: "It Ends with Us",
    price: "159",
    fakePrice: "230",
    img: "/Imgs/Products/itEndsWithUS.jpg",
  },
  {
    pid: 8,
    categoryName: "Romance",
    author: "Own Nicholls",
    name: "Love Unscripted",
    price: "229",
    fakePrice: "435",
    img: "/Imgs/Products/loveUnscripted.jpg",
  },
];

export default Products;
