const Products = [
  {
    pid: 1,
    categoryName: ["Self Help", "Featured Products"],
    author: "Morgan Housel",
    name: "Psychology of Money",
    price: "230",
    fakePrice: "450",
    img: "/Imgs/Products/psychologyOfMoney.jpg",
  },

  {
    pid: 2,
    categoryName: ["Self Help", "Featured Products"],
    author: "Brian Stracy",
    name: "Eat that Frog",
    price: "150",
    fakePrice: "251",
    img: "/Imgs/Products/eatThatFrog.jpg",
  },
  {
    pid: 3,
    categoryName: ["Self Help", "New Arrivals"],
    author: "Napolean Hill",
    name: "Think and Grow Rich",
    price: "235",
    fakePrice: "495",
    img: "/Imgs/Products/thinkAndGrowRich.jpg",
  },
  {
    pid: 4,
    categoryName: ["Self Help", "Featured Products"],
    author: "Dale Carnegie",
    name: "how to win Friends and Influence People",
    price: "230",
    fakePrice: "450",
    img: "/Imgs/Products/howtoWInFriends.jpg",
  },
  {
    pid: 5,
    categoryName: ["Psychology", "Featured Products"],
    author: "Daniel Kehnman",
    name: "Thinking Fast and Slow",
    price: "300",
    fakePrice: "500",
    img: "/Imgs/Products/thinkingFastAndSlow.jpg",
  },
  {
    pid: 6,
    categoryName: ["Psychology", "Most Viewed"],
    author: "David Epstien",
    name: "Range",
    price: "399",
    fakePrice: "699",
    img: "/Imgs/Products/range.jpg",
  },
  {
    pid: 7,
    categoryName: ["Romance", "Most Viewed"],
    author: "Colen Hoover",
    name: "It Ends with Us",
    price: "159",
    fakePrice: "230",
    img: "/Imgs/Products/itEndsWithUS.jpg",
  },
  {
    pid: 8,
    categoryName: ["Romance", "New Arrivals"],
    author: "Own Nicholls",
    name: "Love Unscripted",
    price: "229",
    fakePrice: "435",
    img: "/Imgs/Products/loveUnscripted.jpg",
  },
  {
    pid: 9,
    categoryName: ["Fantasy", "Featured Products"],
    author: "Shane Lee",
    name: "Black Forest",
    price: "230",
    fakePrice: "450",
    img: "/Imgs/Products/blackForest.jpg",
  },
  {
    pid: 10,
    categoryName: ["Thriller", "New Arrivals"],
    author: "Ed Mckdonald",
    name: "Blackwing",
    price: "260",
    fakePrice: "450",
    img: "/Imgs/Products/blackwing.jpg",
  },
  {
    pid: 11,
    categoryName: ["Fantasy", "New Arrivals"],
    author: "S.M Boyce",
    name: "Heritage",
    price: "290",
    fakePrice: "550",
    img: "/Imgs/Products/heritage.jpg",
  },
  {
    pid: 12,
    categoryName: ["Horror", "New Arrivals"],
    author: "Madeleine Roux",
    name: "House Of Furies",
    price: "190",
    fakePrice: "250",
    img: "/Imgs/Products/houseOfFuries.jpg",
  },

  {
    pid: 13,
    categoryName: ["Fantasy", "Most Viewed"],
    author: "Linda. K Hopkins",
    name: "Pursued By a Dragons",
    price: "350",
    fakePrice: "450",
    img: "/Imgs/Products/persuedByADragon.jpg",
  },

  {
    pid: 14,
    categoryName: ["Thriller", "Most Viewed"],
    author: "Lynda Renham",
    name: "Secret and Lies",
    price: "385",
    fakePrice: "460",
    img: "/Imgs/Products/secretAndLies.jpg",
  },
  {
    pid: 15,
    categoryName: ["Thriller", "New Arrivals"],
    author: "B.P Griffith",
    name: "Shadow Land",
    price: "285",
    fakePrice: "360",
    img: "/Imgs/Products/shadowLand.jpg",
  },
  {
    pid: 16,
    categoryName: ["Fantasy", "New Arrivals"],
    author: "Kiersten White",
    name: "The Chaos of Stars",
    price: "485",
    fakePrice: "560",
    img: "/Imgs/Products/theChaosOfStars.jpg",
  },
  {
    pid: 17,
    categoryName: ["Horror", "Featured Products"],
    author: "NIck Thornton",
    name: "The Last Chance Hotel",
    price: "385",
    fakePrice: "460",
    img: "/Imgs/Products/theLastChanceHotel.jpg",
  },
  {
    pid: 18,
    categoryName: ["Thriller", "Featured Products"],
    author: "B.B Griffith",
    name: "The Sleep Walker",
    price: "485",
    fakePrice: "560",
    img: "/Imgs/Products/thSleepWalkers.jpg",
  },
  {
    pid: 19,
    categoryName: ["Fantasy", "Featured Products"],
    author: "Issabel Ianez",
    name: "Woven in Moon",
    price: "185",
    fakePrice: "260",
    img: "/Imgs/Products/wovenInMoonLight.jpg",
  },
  {
    pid: 20,
    categoryName: ["Thriller", "Featured Products"],
    author: "james Nally",
    name: "Dance with The Dead",
    price: "485",
    fakePrice: "560",
    img: "/Imgs/Products/danceWithTheDead.jpg",
  },
];

export default Products;
